Rename config yaml keys camel case
coreos/tectonic-installer pull request #3046
Opened 2018-02-28 13:41 UTC by spangenberg

Keys were pascal cased, now camel cased.

2018-02-28 13:44 UTC, mxinden requested changes
Can you adjust the tests config as well, otherwise your tests will fail: https://github.com/coreos/tectonic-installer/blob/ut2-integration/tests/smoke/aws/vars/aws.basic.yaml

2018-02-28 13:44 UTC, mxinden commented on installer/pkg/config/aws/config.go
> +	Profile                   string    `yaml:"profile,omitempty"`
seems to be wrongly indented.

2018-02-28 13:44 UTC, mxinden commented on installer/pkg/config/gcp/config.go
> +	ConfigVersion            string    `yaml:"configVersion,omitempty"`
go fmt

2018-02-28 13:44 UTC, mxinden commented on installer/pkg/config/types.go
> +	GCP               gcp.Config       `yaml:"gcp,omitempty"`
go fmt

2018-03-01 02:54 UTC, spangenberg commented
retest this

2018-03-01 09:05 UTC, mxinden commented
ok to test

2018-03-01 11:04 UTC, mxinden commented
@spangenberg would you mind adjusting https://github.com/coreos/tectonic-installer/blob/master/tests/rspec/lib/config_file.rb#L21 and all following lines as well to the new casing?

2018-03-01 16:22 UTC, mxinden approved these changes

2018-03-01 16:22 UTC, mxinden commented on installer/pkg/config/types.go
> +	GCP               gcp.Config       `yaml:"gcp,omitempty"`
Seems to be only in my browser, not in `raw` mode.

2018-03-01 16:25 UTC, merged