Simplified Bazel build
coreos/tectonic-installer pull request #3142
Opened 2018-03-28 11:25 UTC by alexsomesan

This change proposed a simplified build flow based on the current Bazel logic.
Notable changes introduced:

* Build only one platform a time. This implies releasing distinct tarballs for distinct architectures.
* Use Bazel datafiles syntax instead of genrule with shell-script to copy static resources.
* Remove the generated examples and replace with static cluster yaml examples.
* Remove some unnecessary rules and dependencies
* The release version is sourced from the `version.bzl` file which can be manipulated by RA.

2018-04-03 15:30 UTC, enxebre commented on BUILD.bazel
> -    outs = ["bin/terraform"],
terraform_fmt currently relies on this output so would need to be updated

2018-04-06 11:16 UTC, alexsomesan commented on WORKSPACE
> +# http_archive(
It's mentioned in the comment above. It's because we need a change from https://github.com/bazelbuild/rules_go/pull/1393 which is not yet released. Once a release is cut, we can revert back to http_archive retrieval. That's why I kept it commented.

2018-04-06 11:16 UTC, alexsomesan commented on BUILD.bazel
> +    "platforms/**/*",
Cool. I'm going to remove it here too. Thanks!

2018-04-06 11:17 UTC, alexsomesan commented on BUILD.bazel
> -    outs = ["bin/terraform"],
ok, I'll put it back then 👍

2018-04-10 08:00 UTC, enxebre commented on BUILD.bazel
> +    "platforms/**/*",
we can remove platforms

2018-04-10 08:01 UTC, enxebre commented on examples/BUILD.bazel
> +exports_files(example_cli_configs)
missing line

2018-04-10 08:01 UTC, enxebre submitted a review, later dismissed

2018-04-10 10:31 UTC, alexsomesan commented on examples/BUILD.bazel
> +exports_files(example_cli_configs)
Fixed it.

2018-04-10 12:14 UTC, enxebre commented
ok to test

2018-04-10 12:14 UTC, enxebre submitted a review, later dismissed

2018-04-10 12:40 UTC, enxebre commented
When running in mac `./tectonic-dev/installer/tectonic` is dropped with no execution perms 644, shouldn't it be 555?
Also could we the tarball name and the export binary path here https://github.com/coreos/tectonic-installer/blob/master/README.md#hacking?

2018-04-11 11:58 UTC, squat requested changes
How does this PR change the tar ball layout? Can you update the Bazel README to reflect this? Also, one of @enxebre’s comments regarding globbing “platforms” should still be addressed I think

2018-04-17 20:58 UTC, alexsomesan commented
@squat Got around to amending the README. PTAL.
Also, smokes should be green now. I'll squash before merging.

2018-04-17 21:52 UTC, alexsomesan commented
Good to review. PTAL

2018-04-18 13:23 UTC, enxebre submitted a review, later dismissed

2018-04-18 13:54 UTC, spangenberg submitted a review, later dismissed

2018-04-23 11:40 UTC, squat approved these changes
Looks good! One more piece of clean up we need to do is to remove the hand-tailored gazelle generated Bazel files in vendor. These had to be modified by hand to support declarative cross-compilation in Bazel but since we are no longer doing this and instead the tarballs only have binaries for a single platform, we can remove those changes. As it stands they will *NOT* be regenerated by gazelle because of the special directive in the files. We simple need to `find ./installer/vendor/ -name *.BAZEL | xargs rm` or the like and then re-run gazelle to regenerate. We can do this in a follow up

2018-04-23 11:41 UTC, squat commented
We need to ensure we coordinate with RA team so they are aware of the new release process requiring one tarball per platform per release

2018-04-23 11:57 UTC, alexsomesan commented
@squat I agree with both points!
Would you say INST-922 would be good opportunity to handle the vendor build files? I'm still hoping we can schedule that one soon, now that the installer backend code is gone too.

On the topic of integration with RA, I'd say the release process as we know it no longer applies at this time. We definitely have to convey these changes to RA nonetheless. Sudha wants to meet this week to discuss the path forward, so we'll touch on these changes and others within the installer.

2018-04-23 12:12 UTC, enxebre approved these changes

2018-04-23 12:50 UTC, merged

2018-07-06 21:31 UTC, wking commented on WORKSPACE
> +# http_archive(
> Once a release is cut, we can revert back to http_archive retrieval.

I've filed openshift/installer#28 with a stab at this.